### ISSUE TITLE
Having flickering issue if using array of image.

### ISSUE THREAD

**Issue by ashivliving** [mladenilic/threesixty.js#21]
Hello, I have forked this repo https://github.com/ashivliving/threesixty.js to stop the flickering, Also I removed the use of sprite. 

Kudos to this repo.

**Comment by mladenilic** [comment]
Looks nice. :)

As a reference, here's is a comment explaining image preloading technique: https://github.com/mladenilic/threesixty.js/issues/16#issuecomment-559543143
