### ISSUE TITLE
Is dist updated to latest version?

### ISSUE THREAD

**Issue by petr24** [mladenilic/threesixty.js#38]
Hey great lightweight library for 360 pictures, I am pulling in the latest version from 'https://cdn.jsdelivr.net/npm/@mladenilic/threesixty.js/dist/threesixty.js'

After I initialize, I set to auto play via

`
threesixty.play(true, 2);
`

However it doesn't stop spinning after two spins. It continues on an infinite loop. 
I looked into the source code, and it looks like logic for handling spin limit isn't there. 

Am I just missing something? 

Thanks.

**Comment by mladenilic** [comment]
PR adding that feature was merged recently. It probably didn't update the built version. I've re-built and pushed it since. Can you try again?

Thanks!
