### ISSUE TITLE
prevent text selection while dragging

### ISSUE THREAD

**Issue by zanona** [mladenilic/threesixty.js#39]
It looks like that, at the moment, when start dragging from inside the container, text on the page is still selected.
Perhaps we could add a `preventDefault` for cancelling those events while dragging here? https://github.com/mladenilic/threesixty.js/blob/e8154acecb46968403f82cddac2b7b71a2bf092a/src/threesixty/events.js#L12

To work around this at the moment, I am having to prevent the default myself on the container by listening the window `mousedown` event against the container target.

```tsx
useEffect(() => {
	function onMouseDown(e) {
		Object.is(e.target, divRef.current) && e.preventDefault();
	}
	addEventListener("mousedown", onMouseDown);
	return () => removeEventListener("mousedown", onMouseDown);
}, [divRef]);

return (
	<div ref={divRef} />
);

```

**Comment by niktor76** [comment]
To set `user-select: none;` styling to the container worked for me.

**Comment by mladenilic** [comment]
I agree. "user-select: none;" is a more straightforward solution.

**Comment by zanona** [comment]
With the css rule, you'd still end selecting text outside the container while dragging, no?

**Comment by niktor76** [comment]
> With the css rule, you'd still end selecting text outside the container while dragging, no?

No, it really works without selecting any text outside of the container.
